import {
  CAR,
  FARM,
  MONITOR,
  PHONE,
  PROFILE_ICON,
  TAP,
  TASK_IMAGE,
} from "@/utils/Exports";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const users_tasks = [
  {
    id: 1,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 2,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 3,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 4,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 5,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 6,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 7,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 8,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 9,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 10,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 11,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 12,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 13,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 14,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 15,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 16,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 17,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 18,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 19,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 20,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 21,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 22,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 23,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 24,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 25,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 26,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 27,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 28,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 29,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 30,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 31,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 32,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 33,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 34,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 35,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 36,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
];

export const template = [
  {
    id: 1,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
];

export const adsData = [
  {
    title: "Map Takeover",
    img: TASK_IMAGE,
    pricetag: "N30,000",
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    img: TASK_IMAGE,
    pricetag: "N30,000",
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    days: "2 days",
    img: TASK_IMAGE,
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
];

export const ParticipantsData = [
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
];

export const AdsTemplate = [
  {
    id: 1,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 7,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 8,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 9,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 10,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 11,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 12,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 13,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 14,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 15,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
];

export const TransactionChartData = {
  "Last 30 days": [
    {
      name: "Jan",
      uv: 4000,
      pv: 4300,
    },
    {
      name: "Feb",
      uv: 3000,
      pv: 4300,
    },
    {
      name: "Mar",
      uv: 2000,
      pv: 4300,
    },
    {
      name: "Apr",
      uv: 2780,
      pv: 4300,
    },
    {
      name: "May",
      uv: 1890,
      pv: 4300,
    },
    {
      name: "Jun",
      uv: 2390,
      pv: 4300,
    },
    {
      name: "Jul",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Aug",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Sep",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Oct",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Nov",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Dec",
      uv: 3490,
      pv: 4300,
    },
  ],
  "Last 7 days": [
    {
      name: "Mon",
      uv: 700,
      pv: 250,
    },
    {
      name: "Tue",
      uv: 300,
      pv: 250,
    },
    {
      name: "Wed",
      uv: 200,
      pv: 250,
    },
    {
      name: "Thu",
      uv: 278,
      pv: 250,
    },
    {
      name: "Fri",
      uv: 180,
      pv: 100,
    },
    {
      name: "Sat",
      uv: 290,
      pv: 100,
    },
    {
      name: "Sun",
      uv: 500,
      pv: 300,
    },
  ],
  Today: [
    {
      name: new Date(),
      uv: 700,
      pv: 250,
    },
  ],
};

export const deposit = [
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
];

export const categories = [
  {
    id: 1,
    title: "Farm",
    img: FARM,
  },
  {
    id: 2,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 3,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 4,
    title: "Motors",
    img: CAR,
  },
  {
    id: 5,
    title: "Plumber",
    img: TAP,
  },

  {
    id: 6,
    title: "Farm",
    img: FARM,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 9,
    title: "Motors",
    img: CAR,
  },
  {
    id: 10,
    title: "Plumber",
    img: TAP,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 9,
    title: "Motors",
    img: CAR,
  },
  {
    id: 10,
    title: "Plumber",
    img: TAP,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
];

export const faketray = [
  {
    id: 1,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 2,
    title: "Profile",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 3,
    title: "Verification",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 4,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 5,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
];
