import { TASK_IMAGE } from "@/utils/Exports";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const users_tasks = [
  {
    id: 1,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 2,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 3,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 4,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 5,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 6,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 7,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 8,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 9,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 10,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 11,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 12,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 13,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 14,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 15,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 16,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 17,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 18,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 19,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 20,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 21,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 22,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 23,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 24,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 25,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 26,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 27,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 28,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 29,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 30,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 31,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 32,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 33,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 34,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 35,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 36,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
];

export const template = [
  {
    id: 1,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
];
