import {
  AIRPLANE_IMG,
  BITCOIN,
  BOOK_IMG,
  CAR,
  CONE_IMG,
  ETH_COIN,
  FARM,
  LITE_COINS,
  MONITOR,
  PAINT_IMG,
  PAN_IMG,
  PHONE,
  PHOTO_ICON,
  PROFILE_ICON,
  REPAIR_IMG,
  SWIM_IMG,
  TAP,
  TASK_IMAGE,
} from "@/utils/Exports";

// eslint-disable-next-line @typescript-eslint/naming-convention
export const users_tasks = [
  {
    id: 1,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 2,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 3,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 4,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 5,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 6,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 7,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 8,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 9,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 10,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 11,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 12,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "new",
  },
  {
    id: 13,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 14,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 15,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 16,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 17,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 18,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 19,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 20,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 21,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 22,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 23,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 24,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "active",
  },
  {
    id: 25,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 26,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 27,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 28,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 29,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 30,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 31,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 32,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 33,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 34,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 35,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
  {
    id: 36,
    title: "Multi-Colored Children’s Sportwear",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    slot_left: "100 slot left",
    time: "2 mins ago",
    location: "Lagos, Nigeria",
    pending: "02:33min left",
    status: "completed",
  },
];

export const template = [
  {
    id: 1,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
];

export const adsData = [
  {
    title: "Map Takeover",
    img: TASK_IMAGE,
    pricetag: "N30,000",
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    img: TASK_IMAGE,
    pricetag: "N30,000",
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    days: "2 days",
    img: TASK_IMAGE,
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
  {
    title: "Map Takeover",
    pricetag: "N30,000",
    img: TASK_IMAGE,
    days: "2 days",
    time: "48 hours",
  },
];

export const ParticipantsData = [
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
  {
    profile_image: PROFILE_ICON,
    name: "Mike Ross",
    email: "@MikeRossBoss",
  },
];

export const AdsTemplate = [
  {
    id: 1,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 2,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 3,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 4,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 6,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 5,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 7,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 8,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 9,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 10,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 11,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 12,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 13,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 14,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
  {
    id: 15,
    title: "10 Baskets of Tomatoes",
    img: TASK_IMAGE,
    price_tag: "N4,800,000",
    service: "Food Services",
    company: "Coker & Sons Ltd.",
    location: "Lagos, Nigeria",
  },
];

export const TransactionChartData = {
  "Last 30 days": [
    {
      name: "Jan",
      uv: 4000,
      pv: 4300,
    },
    {
      name: "Feb",
      uv: 3000,
      pv: 4300,
    },
    {
      name: "Mar",
      uv: 2000,
      pv: 4300,
    },
    {
      name: "Apr",
      uv: 2780,
      pv: 4300,
    },
    {
      name: "May",
      uv: 1890,
      pv: 4300,
    },
    {
      name: "Jun",
      uv: 2390,
      pv: 4300,
    },
    {
      name: "Jul",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Aug",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Sep",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Oct",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Nov",
      uv: 3490,
      pv: 4300,
    },
    {
      name: "Dec",
      uv: 3490,
      pv: 4300,
    },
  ],
  "Last 7 days": [
    {
      name: "Mon",
      uv: 700,
      pv: 250,
    },
    {
      name: "Tue",
      uv: 300,
      pv: 250,
    },
    {
      name: "Wed",
      uv: 200,
      pv: 250,
    },
    {
      name: "Thu",
      uv: 278,
      pv: 250,
    },
    {
      name: "Fri",
      uv: 180,
      pv: 100,
    },
    {
      name: "Sat",
      uv: 290,
      pv: 100,
    },
    {
      name: "Sun",
      uv: 500,
      pv: 300,
    },
  ],
  Today: [
    {
      name: new Date(),
      uv: 700,
      pv: 250,
    },
  ],
};

export const deposit = [
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
  {
    amount: "500",
    date: "12/03/20",
  },
];

export const categories = [
  {
    id: 1,
    title: "Farm",
    img: FARM,
  },
  {
    id: 2,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 3,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 4,
    title: "Motors",
    img: CAR,
  },
  {
    id: 5,
    title: "Plumber",
    img: TAP,
  },

  {
    id: 6,
    title: "Farm",
    img: FARM,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 9,
    title: "Motors",
    img: CAR,
  },
  {
    id: 10,
    title: "Plumber",
    img: TAP,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 9,
    title: "Motors",
    img: CAR,
  },
  {
    id: 10,
    title: "Plumber",
    img: TAP,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
  {
    id: 7,
    title: "IT Engineer",
    img: MONITOR,
  },
  {
    id: 8,
    title: "Phones",
    img: PHONE,
  },
];

export const faketray = [
  {
    id: 1,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 2,
    title: "Profile",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 3,
    title: "Verification",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 4,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
  {
    id: 5,
    title: "Wallet",
    text: "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor",
  },
];

export const interestData = [
  {
    id: 1,
    img: SWIM_IMG,
    title: "Swimming",
  },
  {
    id: 2,
    img: CONE_IMG,
    title: "Partying",
  },
  {
    id: 3,
    img: AIRPLANE_IMG,
    title: "Travelling",
  },
  {
    id: 4,
    img: REPAIR_IMG,
    title: "Repairs",
  },
  {
    id: 5,
    img: PHOTO_ICON,
    title: "Photography",
  },
  {
    id: 6,
    img: PAN_IMG,
    title: "Cooking",
  },
  {
    id: 7,
    img: BOOK_IMG,
    title: "Learning",
  },
  {
    id: 8,
    img: PAINT_IMG,
    title: "Painting",
  },
];

export const dropdowndata = [
  {
    id: "1",
    label: "Hey what up",
  },
  {
    id: "2",
    label: "Hey what up",
  },
  {
    id: "3",
    label: "Hey what up",
  },
];
export const BanksData = [
  {
    id: "1",
    label: "Access bank",
  },
  {
    id: "2",
    label: "Guarantee Trust Bank",
  },
  {
    id: "3",
    label: "FCMB bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
  {
    id: "4",
    label: "Union bank",
  },
];

export const bestPerformanceData = [
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
  {
    name: "Adewale Adedamola",
    userimg: TASK_IMAGE,
    username: "@adedamola456",
    referals: "66",
    trans: "66",
    ratings: "66",
  },
];

export const ratingsdata = [
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "5,786",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
  {
    name: "John Tommy",
    img: TASK_IMAGE,
    location: "Lagos, Nigeria",
    peoplerate: "4,567",
  },
];

export const filterData = [
  {
    id: "1",
    list: "Name",
  },
  {
    id: "2",
    list: "Location",
  },
  {
    id: "3",
    list: "Ratings",
  },
  {
    id: "4",
    list: "Verification",
  },
  {
    id: "5",
    list: "Status",
  },
];

export const TABLE_DATA = [
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
  {
    img: TASK_IMAGE,
    username: "@adedamola456",
    ratings: "4.5",
    referal_code: "68779729",
    total_amnt: "34,000",
    people: "38",
    level: "1",
    date: "	15-08-2020 10-35-54",
    status: "	Successful",
  },
];
export const fakedata = [
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
  {
    name: "michale mike",
    location: "lekki",
    age: "32",
    status: "good",
  },
];

export const usersLists = [
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
  {
    img: TASK_IMAGE,
    name: "Adewale Adedamola",
    username: "@adedamola456",
    acct_no: "3099678981",
    bank: "First Bank",
    amount: "28,000",
    ratings: "4.5",
    verification: "Verified",
    status: "Active",
    data: "	15-08-2020 10-35-54",
  },
];

export const highlitedata = [
  {
    analysis: "5769",
    tags: "Top category",
    percentage: "-63.8",
  },
  {
    analysis: "30",
    tags: "Top interests",
    percentage: "8",
  },
  {
    analysis: "30",
    tags: "Top Location",
    percentage: "8",
  },
  {
    analysis: "30",
    tags: "Purchases",
    percentage: "8",
  },
  {
    analysis: "30",
    tags: "Spend",
    percentage: "8",
  },
  {
    analysis: "30",
    tags: "Requests out",
    percentage: "8",
  },
  {
    analysis: "30",
    tags: "Tasks completed",
    percentage: "8",
  },
];

export const Adsdata = [
  {
    id: "1",
    analysis: "5769",
    tags: "Account reached",
    percentage: "-63.8",
  },
  {
    id: "2",
    analysis: "30",
    tags: "Account reached",
    percentage: "-63.8",
  },
  {
    id: "3",
    analysis: "30",
    tags: "Profile clicked",
    percentage: "8",
  },
];

export const productsListed = [
  {
    img: TASK_IMAGE,
    name: "Medplus Surulere",
    username: "@adedamola456",
  },
  {
    img: TASK_IMAGE,
    name: "Medplus Surulere",
    username: "@adedamola456",
  },
  {
    img: TASK_IMAGE,
    name: "Medplus Surulere",
    username: "@adedamola456",
  },
  {
    img: TASK_IMAGE,
    name: "Medplus Surulere",
    username: "@adedamola456",
  },
  {
    img: TASK_IMAGE,
    name: "Medplus Surulere",
    username: "@adedamola456",
  },
];

export const cryptoLists = [
  {
    id: "1",
    name: "BTC",
    address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    img: BITCOIN,
  },
  {
    id: "2",
    name: "ETH",
    address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    img: ETH_COIN,
  },
  {
    id: "3",
    name: "LTC",
    address: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    img: LITE_COINS,
  },
];

export const usertransactions = [
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
  {
    username: "@adedamola456",
    transaction_id: "1BvBMSEYstWetqTFn5Au4m4GFg7xJaNVN2",
    date: "12/03/20",
    amount: "500",
  },
];

export const userActivities = [
  {
    title: "SUSD Purchased",
    details: "User purchased $567 from spottr ref:",
    link: "https;//spottradmin.8783/uynbunbjahn",
    date: "12 Aug.",
  },
  {
    title: "Fiat Deposited",
    details: "User purchased $567 from spottr ref:",
    link: "https;//spottradmin.8783/uynbunbjahn",
    date: "12 Aug.",
  },
  {
    title: "Phone number verified",
    details: "Phone number verified",

    date: "12 Aug.",
  },
  {
    title: "Password changed",
    details: "User updated  profile settings",

    date: "12 Aug.",
  },
  {
    title: "Withdreew Referral",
    details: "user withdrew $567 from referral system",

    date: "12 Aug.",
  },
  {
    title: "Item Sold",
    details:
      "user sold Multi-Colored Children’s Sportwear. Quantity: 10  N4,800,000  ref: ",
    link: "https;//spottradmin.8783/uynbunbjahn",
    date: "12 Aug.",
  },
  {
    title: "Item Sold",
    details:
      "user sold Multi-Colored Children’s Sportwear. Quantity: 10  N4,800,000  ref: ",
    link: "https;//spottradmin.8783/uynbunbjahn",
    date: "12 Aug.",
  },
];
